### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OksanaSava**
changed a file

### CODE REVIEW

**Comment by nadiazhyvan** [comment]
What changes&

**Comment by OksanaSava** [comment]
some changes

**Review by nadiazhyvan — DISMISSED** [review]
&

**Comment by nadiazhyvan** [comment]
https://github.com/nadiazhyvan/new-project/invitations

2018-04-10 13:15 GMT+03:00 OksanaSava <notifications@github.com>:

**Comment by nadiazhyvan** [comment]
https://github.com/nadiazhyvan/it-25/invitations


2018-04-10 20:04 GMT+03:00 Надя Живан <nadushetcka@gmail.com>:

**Comment by OksanaSava** [comment]
https://github.com/OksanaSava/Informational-technologies/invitations



2018-04-10 20:33 GMT+03:00 nadiazhyvan <notifications@github.com>:

**Pull request merged**
